### ISSUE TITLE
I need to use this application from android phone

### ISSUE THREAD

**Issue by Cretu93** [Gipsonek/ArduPod#3]
Hello,

How can I use processing app on android phone.
I don't see where you use bluetooth comnunication with another device that can send commands.
I need to use your buttons from app to send comand through bluetooth not serial.
Could you please help me?

**Comment by jgromes** [comment]
Unfortunately, the processing app was written to be only used on PC. Even though Processing IDE has an "Android" mode, I don't have any experience with it. Besides, the way Bluetooth communication is handled on Android devices is fundamentally different from the approach I used: in the app, the commands are sent to Serial port which has USB Bluetooth adapter connected to it. Also, the app requires some Processing libraries, and I'm not sure if they would work on Android.

I doubt you will be able to use this app from Android phone as it is written right now - that would probably require substantial modifications. Instead, I would recommend using Android studio to write a new app. As a sort of starting point, you can take a look at my [ArduRover](https://github.com/jgromes/ArduRover) project. In the `android` directory, you will find an Android app that can send data either through Bluetooth, or through USB port.
