### ISSUE TITLE
Any way I can use an Uno by doing the possessing elsewhere?

### ISSUE THREAD

**Issue by Chroniton4X** [Gipsonek/ArduPod#4]
Hi, I have designed and 3d printed my own 2 DOF hexapod based around the Arduino Uno (particularly its dimensions) prior to finding out its lack of processing power for IK. Switching to the mega would mean I need to redesign and print the whole chassis again. Is there any way I could do all the processing on an external laptop or Arduino Mega and just send the servo positions to the Uno onboard the robot over Bluetooth?

**Comment by jgromes** [comment]
I don't see why not - since most Bluetooth devices behave like simple serial port, it shouldn't be that hard. Speed is going to be critical, but if you design the communication right (e.g. not wasting space with strings when you can use just few bytes) and set high baud rate, it should work.

**Comment by Chroniton4X** [comment]
Thank you for responding so fast! Great to hear it is possible. This is my first Arduino project I need all the help I can get lol.  Do you happen to know of any programs that will let me run the possessing side of the code on a Windows pc and send the data over Bluetooth?

**Comment by jgromes** [comment]
The simplest one is probably Processing (https://processing.org/), there are loads of tutorials on connecting it to Arduino. Just keep in mind that even though it looks similar to Arduino IDE, the language is Java, not C/C++.

If you're looking something more professional, I suggest Visual Studio and writing the PC app in C#. Working with GUI elements is much easier than in Processing.

**Comment by Chroniton4X** [comment]
I just got a cheap Arduino Mega clone and I'm going to design and print a new chassis for it. I want to add some more sensors to the robot later and maybe control it with a smartphone so I will need more processing power anyway. Also, it should be easier since I don't have to convert to Java.  

     I can do 3d modeling and electronics but I'm new to programming in C++. This project is mostly for teaching my self C++ and the Arduino so I make design, wire, and program things.
